### ISSUE TITLE
v2: parser crash on incomplete table

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#579]
**Describe the bug**
Parser crashes on standard table when document ends before final `]`.

```
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 984 [running]:
testing.tRunner.func1.2({0x60b580, 0xc0002f62a0})
        /home/x/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /home/x/go/src/testing/testing.go:1212 +0x218
panic({0x60b580, 0xc0002f62a0})
        /home/x/go/src/runtime/panic.go:1038 +0x215
github.com/pelletier/go-toml/v2.expect(...)
        /home/x/src/github.com/pelletier/go-toml/parser.go:1033
github.com/pelletier/go-toml/v2.(*parser).parseStdTable(0xc00041b7a0, {0xc0004434b8, 0x4, 0x8})
        /home/x/src/github.com/pelletier/go-toml/parser.go:198 +0x34a
github.com/pelletier/go-toml/v2.(*parser).parseTable(0xc00041b7a0, {0xc0004434b8, 0xf, 0x0})
        /home/x/src/github.com/pelletier/go-toml/parser.go:146 +0x39
github.com/pelletier/go-toml/v2.(*parser).parseExpression(0x203000, {0xc0004434b8, 0x199, 0x690f95})
        /home/x/src/github.com/pelletier/go-toml/parser.go:120 +0x9f
github.com/pelletier/go-toml/v2.(*parser).NextExpression(0xc00041b7a0)
        /home/x/src/github.com/pelletier/go-toml/parser.go:61 +0x119
github.com/pelletier/go-toml/v2.(*decoder).nextExpr(...)
        /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:143
github.com/pelletier/go-toml/v2.(*decoder).fromParser(0xc0000a9e90, {0x5e3d40, 0xc00041f300, 0x7cc640})
        /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:191 +0x65
github.com/pelletier/go-toml/v2.(*decoder).FromParser(0xc0000a9e90, {0x5d52e0, 0xc00041f300})
        /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:177 +0xf8
github.com/pelletier/go-toml/v2.Unmarshal({0xc0004434b8, 0x4, 0x8}, {0x5d52e0, 0xc00041f300})
        /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:27 +0x112
```
**To Reproduce**
```go
var v interface{}
_ = toml.Unmarshal([]byte(`[foo`), &v)
```

**Expected behavior**
No panic.

**Versions**
 - go-toml: v2 8be357dfa190aed96094e4825ec04cb1d53df452
 - go version go1.17 linux/amd64

**Additional context**
https://play.golang.org/p/R6b3zEVn6W7

Found while playing with [Go fuzzbeta](https://go.dev/blog/fuzz-beta).

**Comment by pelletier** [comment]
Thanks for catching this! I'll take a look.

I haven't played with gofuzz yet. If you think there's anything that would be useful to add to go-toml to support fuzzing easily let me know.

**Comment by pelletier** [comment]
Should be fixed with https://github.com/pelletier/go-toml/commit/40cfb6f45824f8f5cd16957894b5c42e10b65f6e. Let me know if not!
