### ISSUE TITLE
v2: panic in danger.SubsliceOffset during Unmarshal

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#581]
**Describe the bug**
```
    panic: subslice address (0) is before data address (824633851432)
    goroutine 1008 [running]:
    runtime/debug.Stack()
        /home/x/sdk/gotip/src/runtime/debug/stack.go:24 +0x65
    testing.tRunner.func1.2({0x6303e0, 0xc00041c3d0})
        /home/x/sdk/gotip/src/testing/testing.go:1281 +0x267
    testing.tRunner.func1()
        /home/x/sdk/gotip/src/testing/testing.go:1288 +0x218
    panic({0x6303e0, 0xc00041c3d0})
        /home/x/sdk/gotip/src/runtime/panic.go:1038 +0x215
    github.com/pelletier/go-toml/v2/internal/danger.SubsliceOffset({0xc00001fe28, 0x4, 0x8}, {0x0, 0x0, 0x0})
        /home/x/src/github.com/pelletier/go-toml/internal/danger/danger.go:16 +0x28e
    github.com/pelletier/go-toml/v2.wrapDecodeError({0xc00001fe28, 0x4, 0x8}, 0xc0003fd300)
        /home/x/src/github.com/pelletier/go-toml/errors.go:108 +0x5c
    github.com/pelletier/go-toml/v2.(*decoder).FromParser(0xc0000a96d0, {0x61eb40, 0xc00041c3b0})
        /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:184 +0x165
    github.com/pelletier/go-toml/v2.Unmarshal({0xc00001fe28, 0x4, 0x8}, {0x61eb40, 0xc00041c3b0})
        /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:27 +0x112
    github.com/pelletier/go-toml/v2.FuzzUnmarshal.func1(0xc00045dd40, {0xc00001fe28, 0x4, 0x8})
        /home/x/src/github.com/pelletier/go-toml/fuzz_test.go:43 +0x56
    reflect.Value.call({0x62afa0, 0x691bf0, 0x13}, {0x672339, 0x4}, {0xc000096e70, 0x2, 0x2})
        /home/x/sdk/gotip/src/reflect/value.go:543 +0x814
    reflect.Value.Call({0x62afa0, 0x691bf0, 0xc000069380}, {0xc000096e70, 0x2, 0x2})
        /home/x/sdk/gotip/src/reflect/value.go:339 +0xc5
    testing.(*F).Fuzz.func1.1(0xc00000c1e0)
        /home/x/sdk/gotip/src/testing/fuzz.go:389 +0x1c6
    testing.tRunner(0xc00045dd40, 0xc000103000)
        /home/x/sdk/gotip/src/testing/testing.go:1335 +0x102
    created by testing.(*F).Fuzz.func1
        /home/x/sdk/gotip/src/testing/fuzz.go:378 +0x505
```

**To Reproduce**
https://play.golang.org/p/jiVaJy17lXw
```go
var v interface{}
toml.Unmarshal([]byte(`P=[#`), &v)
```

**Expected behavior**
No panic.

**Versions**
 - go-toml: v2 40cfb6f45824f8f5cd16957894b5c42e10b65f6e
 - go version devel go1.17-9c56a64673 Fri Sep 3 18:34:56 2021 +0000 linux/amd64

**Comment by pelletier** [comment]
Thank you for finding this! Should be fixed by https://github.com/pelletier/go-toml/commit/7e2fa1bc80f68e42c9f372db5f4f575991d5c827.
