### ISSUE TITLE
v2: bounds out of range panic in parser.scanDateTime

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#585]
**Describe the bug**
Given `a=1979-05127T 0`:
```
        panic: runtime error: slice bounds out of range [14:13]
        goroutine 3705475 [running]:
        runtime/debug.Stack()
                /home/x/sdk/gotip/src/runtime/debug/stack.go:24 +0x90
        testing.tRunner.func1.2({0x6f82e0, 0xc0000e6de0})
                /home/x/sdk/gotip/src/testing/testing.go:1281 +0x267
        testing.tRunner.func1()
                /home/x/sdk/gotip/src/testing/testing.go:1288 +0x218
        panic({0x6f82e0, 0xc0000e6de0})
                /home/x/sdk/gotip/src/runtime/panic.go:1038 +0x215
        github.com/pelletier/go-toml/v2.(*parser).scanDateTime(0xc007ee9260, {0xc00001b3c2, 0xd, 0x1e})
                /home/x/src/github.com/pelletier/go-toml/parser.go:920 +0x6f0
        github.com/pelletier/go-toml/v2.(*parser).parseIntOrFloatOrDateTime(0xc007ee9260, {0xc00001b3c2, 0xd, 0x1e})
                /home/x/src/github.com/pelletier/go-toml/parser.go:844 +0x9ac
        github.com/pelletier/go-toml/v2.(*parser).parseVal(0xc007ee9260, {0xc00001b3c2, 0xd, 0x1e})
                /home/x/src/github.com/pelletier/go-toml/parser.go:316 +0xde9
        github.com/pelletier/go-toml/v2.(*parser).parseKeyval(0xc007ee9260, {0xc00001b3c0, 0xf, 0x20})
                /home/x/src/github.com/pelletier/go-toml/parser.go:229 +0x529
        github.com/pelletier/go-toml/v2.(*parser).parseExpression(0x1, {0xc00001b3c0, 0xf, 0x20})
                /home/x/src/github.com/pelletier/go-toml/parser.go:122 +0x2e5
        github.com/pelletier/go-toml/v2.(*parser).NextExpression(0xc007ee9260)
                /home/x/src/github.com/pelletier/go-toml/parser.go:61 +0x212
        github.com/pelletier/go-toml/v2.(*decoder).nextExpr(...)
                /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:143
        github.com/pelletier/go-toml/v2.(*decoder).fromParser(0xc0001156d0, {0x6c8040, 0xc00858e200, 0x6670a417feb8})
                /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:191 +0x9f
        github.com/pelletier/go-toml/v2.(*decoder).FromParser(0xc0001156d0, {0x6b7b40, 0xc00858e200})
                /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:177 +0x2dc
        github.com/pelletier/go-toml/v2.Unmarshal({0xc00001b3c0, 0xf, 0x20}, {0x6b7b40, 0xc00858e200})
                /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:27 +0x132
```

**To Reproduce**
https://play.golang.org/p/5-Jhccn9gYk
```go
toml.Unmarshal([]byte(`a=1979-05127T 0`), &v)
```

**Expected behavior**
No panic.

**Versions**
 - go-toml: v2 4a5ae9e81e09e3cc5197fccde9105e9fa5ff65b9
 - go version devel go1.17-9c56a64673 Fri Sep 3 18:34:56 2021 +0000 linux/amd64

Found with Go dev.fuzz.

**Comment by pelletier** [comment]
Really didn't pay enough attention to bounds checking on that rewrite :(. Thank you for finding those.

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/fa56f48dafbcbb560f5959149e64683eccac6341
