### ISSUE TITLE
v2: panic in error handling of truncated array

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#588]
**Describe the bug**
```
        panic: subslice address (0) is before data address (824769409104)
        goroutine 746627 [running]:
        github.com/pelletier/go-toml/v2/internal/danger.SubsliceOffset({0xc008167050, 0x5, 0x10}, {0x0, 0x0, 0x0})
                /home/x/src/github.com/pelletier/go-toml/internal/danger/danger.go:16 +0x3b7
        github.com/pelletier/go-toml/v2.wrapDecodeError({0xc008167050, 0x5, 0x10}, 0xc008274b40)
                /home/x/src/github.com/pelletier/go-toml/errors.go:108 +0x6b
        github.com/pelletier/go-toml/v2.(*decoder).FromParser(0xc00b6996d0, {0x6b7b40, 0xc0080cb460})
                /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:184 +0x365
        github.com/pelletier/go-toml/v2.Unmarshal({0xc008167050, 0x5, 0x10}, {0x6b7b40, 0xc0080cb460})
                /home/x/src/github.com/pelletier/go-toml/unmarshaler.go:27 +0x132
```

**To Reproduce**
https://play.golang.org/p/e6lH2SXIqwP
```go
toml.Unmarshal([]byte(`a=[1#`), &v)
```

**Expected behavior**
No panic.

**Versions**
 - go-toml: v2 a0d685d4822fed8f5589a75bbf6cf734231e1a9c
 - go version devel go1.17-9c56a64673 Fri Sep 3 18:34:56 2021 +0000 linux/amd64

**Additional context**
Found with Go dev.fuzz.

You may notice that I figured out how to tell Go playground to use the latest commit.  That's pretty handy.

**Comment by pelletier** [comment]
> You may notice that I figured out how to tell Go playground to use the latest commit. That's pretty handy.

Very nice! Thanks for sharing!
