### ISSUE TITLE
Inline tables panic when going through ToString

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#64]
```toml
name = { first = "Tom", last = "Preston-Werner" }
points = { x = 1, y = 2 }
```

seems to panic

```
panic: unsupported value type: &{map[first:0x8202aa580 last:0x8202aa5c0] {0 0}}

goroutine 1 [running]:
github.com/robmuh/go-toml.toTomlValue(0x16fc60, 0x8202aa560, 0x0, 0x0, 0x0)
    /Users/robmuh/go/src/github.com/robmuh/go-toml/tomltree_conversions.go:67 +0x5f3
github.com/robmuh/go-toml.(*TomlTree).toToml(0x8202aa520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/robmuh/go/src/github.com/robmuh/go-toml/tomltree_conversions.go:103 +0x11db
github.com/robmuh/go-toml.(*TomlTree).ToString(0x8202aa520, 0x0, 0x0)
    /Users/robmuh/go/src/github.com/robmuh/go-toml/tomltree_conversions.go:114 +0x45
main.main()
    /Users/robmuh/go/src/github.com/toml-spec/tomll/cmd/tomll/main.go:18 +0x210
```

**Comment by pelletier** [comment]
@robmuh I don't seem to be able to reproduce the panic error. Do you mind providing

1. a complete Go file that reproduces the issue
2. which go-toml revision you use.
3. which version of Go you use.

Thanks!

**Comment by robmuh** [comment]
```go
package main

import (
        "fmt"
        "os"

        "github.com/robmuh/go-toml"
)

func main() {
        if len(os.Args) >= 2 { 
                for _, f := range os.Args[1:] {
                        m, e := toml.LoadFile(f)
                        if e != nil {
                                fmt.Println(e)
                        } else {
                                fmt.Print(m.ToString())
                        }   
                }   
        }   
}
```

```
go version go1.5 darwin/amd64
```
```properties
remote.origin.url=git@github.com:robmuh/go-toml.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.pelletier/tomltree-to-map.remote=origin
branch.pelletier/tomltree-to-map.merge=refs/heads/pelletier/tomltree-to-map
```
I read elsewhere that you have merged @bep's branch so I will retry using `master` on your main repo, but this was a simple fork so I could change the default to `pelletier/tomltree-to-map` for testing and potentially add some `*_test*` files to it, which I didn't need to do in the end.

**Comment by robmuh** [comment]
Confirmed in the new `master` branch, and yes, I see now it is likely `ToString` and not `ToMap` on which it is dependent.

**Comment by pelletier** [comment]
@robmuh I think I fixed it. Do you mind trying out that branch? https://github.com/pelletier/go-toml/pull/67

**Comment by pelletier** [comment]
Fix merged.
