### ISSUE TITLE
Disallow invalid dates

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#676]
**Describe the bug**
Two issues:

Given `a=0000-01-00` accepts the day value as valid.

Given `a=0000-00-00`, go-toml panics:
```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/pelletier/go-toml/v2.daysIn(...)
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/decode.go:491
github.com/pelletier/go-toml/v2.isValidDate(...)
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/decode.go:465
github.com/pelletier/go-toml/v2.parseLocalDate({0xc000126002, 0xa, 0x477328})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/decode.go:55 +0x23e
github.com/pelletier/go-toml/v2.(*decoder).unmarshalLocalDate(0xc000106e98, 0xc00012a070, {0x4c3080, 0xc00010a280, 0x10})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:741 +0x5f
github.com/pelletier/go-toml/v2.(*decoder).handleValue(0x4c0f01, 0xc00012a070, {0x4c3080, 0xc00010a280, 0x10})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:609 +0x1cf
github.com/pelletier/go-toml/v2.(*decoder).handleKeyValueInner(0x4bdf40, {0x1, 0x0}, 0x4c0fc0, {0x4c3080, 0xc00010a280, 0x7f3f8d009100})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:951 +0x8c
github.com/pelletier/go-toml/v2.(*decoder).handleKeyValuePart(0xc000106e98, {0x1, 0xc00012a038}, 0x7f3f8d2b2428, {0x4c44c0, 0xc00010c1b0, 0x7f3fb3d3fa68})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:995 +0x545
github.com/pelletier/go-toml/v2.(*decoder).handleKeyValuePart(0xc000106e98, {0x1, 0xc00012a038}, 0xc000106d10, {0x4c3080, 0xc00010a260, 0x1})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:1033 +0x6aa
github.com/pelletier/go-toml/v2.(*decoder).handleKeyValueInner(0x1, {0x1, 0xc00012a038}, 0xc000106d08, {0x4c3080, 0xc00010a260, 0xffffffffffffffff})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:947 +0x71
github.com/pelletier/go-toml/v2.(*decoder).handleKeyValue(0xc000106e98, 0xc00012a000, {0x4c3080, 0xc00010a260, 0xc})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:933 +0xa5
github.com/pelletier/go-toml/v2.(*decoder).handleRootExpression(0xc000106e98, 0xc00012a000, {0x4c3080, 0xc00010a260, 0x4c3080})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:234 +0xa9
github.com/pelletier/go-toml/v2.(*decoder).fromParser(0xc000106e98, {0x4c3080, 0xc00010a260, 0x4c44c0})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:200 +0xa9
github.com/pelletier/go-toml/v2.(*decoder).FromParser(0xc000106e98, {0x4bdf40, 0xc00010a260})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:185 +0x1e7
github.com/pelletier/go-toml/v2.Unmarshal({0xc000126000, 0xc, 0xc}, {0x4bdf40, 0xc00010a260})
	/tmp/gopath2844455945/pkg/mod/github.com/pelletier/go-toml/v2@v2.0.0-beta.4.0.20211114000453-64fe47161f06/unmarshaler.go:28 +0x112
main.main()
	/tmp/sandbox993221366/prog.go:10 +0x67
```

**To Reproduce**
https://go.dev/play/p/fjUJEXx2kPP
```go
toml.Unmarshal([]byte("a=0000-01-00"), &v)
```

**Expected behavior**
Obviously, we never want a panic.  I expected errors about month=0 and day=0.

**Versions**
 - go-toml: 64fe47161f06327328066634453811622f664583
 - go version go1.17.3 linux/amd64

**Additional context**
Found while doing differential fuzzing against [toml.dart](https://github.com/just95/toml.dart).

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/8eae15b2eea879e3e7627c8b50763c7ed9a042db. Thank you!
