### ISSUE TITLE
Panic on trailing invalid key

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#714]
**Describe the bug**
Given document of `0.`, `go-toml` panics:
```
$ echo -n "0." | gotoml-test-decoder
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/pelletier/go-toml/v2.(*parser).parseSimpleKey(0x200, {0xc0000c6002, 0x1, 0x200})
        /x/src/github.com/pelletier/go-toml/parser.go:700 +0x1cd
github.com/pelletier/go-toml/v2.(*parser).parseKey(0xc0000c8000, {0xc0000c6000, 0xc0000001a0, 0x6bad9aecaea8})
        /x/src/github.com/pelletier/go-toml/parser.go:677 +0x2f7
github.com/pelletier/go-toml/v2.(*parser).parseKeyval(0xc0000c8000, {0xc0000c6000, 0x2, 0x200})
        /x/src/github.com/pelletier/go-toml/parser.go:208 +0x17c
github.com/pelletier/go-toml/v2.(*parser).parseExpression(0xc0000ca000, {0xc0000c6000, 0x40, 0x51e2a0})
        /x/src/github.com/pelletier/go-toml/parser.go:122 +0xa7
github.com/pelletier/go-toml/v2.(*parser).NextExpression(0xc0000c8000)
        /x/src/github.com/pelletier/go-toml/parser.go:62 +0x119
github.com/pelletier/go-toml/v2.(*decoder).nextExpr(...)
        /x/src/github.com/pelletier/go-toml/unmarshaler.go:168
github.com/pelletier/go-toml/v2.(*decoder).fromParser(0xc0000ca000, {0x4e1d80, 0xc0000b4018, 0x100010000488a26})
        /x/src/github.com/pelletier/go-toml/unmarshaler.go:222 +0x65
github.com/pelletier/go-toml/v2.(*decoder).FromParser(0xc0000ca000, {0x4da800, 0xc0000b4018})
        /x/src/github.com/pelletier/go-toml/unmarshaler.go:208 +0x1e7
github.com/pelletier/go-toml/v2.(*Decoder).Decode(0xc00009aec8, {0x4da800, 0xc0000b4018})
        /x/src/github.com/pelletier/go-toml/unmarshaler.go:112 +0x1d2
github.com/pelletier/go-toml/v2/testsuite.DecodeStdin()
        /x/src/github.com/pelletier/go-toml/testsuite/testsuite.go:39 +0x7c
main.main()
        /x/src/github.com/pelletier/go-toml/cmd/gotoml-test-decoder/main.go:20 +0xb9
```

**To Reproduce**
https://go.dev/play/p/nTrQFPp1mOH
```go
toml.Unmarshal([]byte("0."), &v)
```

**Expected behavior**
Not a panic.  Expected error for invalid input.

**Versions**
 - go-toml: d58eb50ebfb929b84ef2af730b2f8503aa4a25fb
 - go version go1.17.5 linux/amd64

**Additional context**
Found while fuzzing (but not differential fuzzing this time).

**Comment by moorereason** [comment]
Issue exists with trailing whitespace as well:  `[]byte("0. ")`

**Comment by pelletier** [comment]
Fixed by https://github.com/pelletier/go-toml/commit/128b7a8bfbd341c1e7d58adcb02911c9b6abf4fe
